### ISSUE TITLE
"Create first IDE app" tutorial: Application.e4xmi not found

### ISSUE THREAD

**Issue by klemensedler** [akhikhl/wuff#100]
I have just begun looking into wuff and I would really like to use it for a few Eclipse-based projects.

When I tried out the IDE Application tutorial, I could however not even complete the first page:
After creating the build.gradle file and calling "gradle build", the artifacts in builds/lib and builds/output are created just fine and the build completes successfully (My setup: Fedora Linux 64bit, Oracle Java 8, Gradle 2.9).
But when I want to start the application (both from command line and via GUI), no window comes up, and I find a FileNotFoundException for /Application.e4xmi in workspace/.metadata/.log:

> !SESSION 2015-11-25 14:57:06.092 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=1.8.0_66
> java.vendor=Oracle Corporation
> BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_GB
> Command-line arguments:  -os linux -ws gtk -arch x86_64
> 
> !ENTRY org.eclipse.e4.ui.workbench 4 0 2015-11-25 14:57:07.050
> !MESSAGE Unable to load resource platform:/plugin/MyIdeApp/Application.e4xmi
> !STACK 0
> org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException:  java.io.FileNotFoundException: /Application.e4xmi
>   at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.handleDemandLoadException(ResourceSetImpl.java:319)
>   at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:278)
>   at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.getResource(ResourceSetImpl.java:406)
>   at org.eclipse.e4.ui.internal.workbench.ResourceHandler.getResource(ResourceHandler.java:350)
>   at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadResource(ResourceHandler.java:326)
>     at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadMostRecentModel(ResourceHandler.java:243)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:435)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:260)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:146)
>     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
>     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
>     at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
>     at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
> Caused by: java.io.FileNotFoundException: /Application.e4xmi
>     at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:37)
>     at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:169)
>     at java.net.URL.openConnection(URL.java:972)
>     at org.eclipse.core.internal.boot.PlatformURLConnection.connect(PlatformURLConnection.java:110)
>     at org.eclipse.core.internal.boot.PlatformURLConnection.connect(PlatformURLConnection.java:91)
>     at org.eclipse.core.internal.boot.PlatformURLConnection.getInputStream(PlatformURLConnection.java:229)
>     at org.eclipse.emf.ecore.resource.impl.URIHandlerImpl.createInputStream(URIHandlerImpl.java:207)
>     at org.eclipse.emf.ecore.resource.impl.ExtensibleURIConverterImpl.createInputStream(ExtensibleURIConverterImpl.java:360)
>     at org.eclipse.emf.ecore.resource.impl.ResourceImpl.load(ResourceImpl.java:1269)
>     at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoad(ResourceSetImpl.java:259)
>     at org.eclipse.emf.ecore.resource.impl.ResourceSetImpl.demandLoadHelper(ResourceSetImpl.java:274)
>     ... 20 more
> 
> !ENTRY org.eclipse.e4.ui.workbench 4 0 2015-11-25 14:57:07.051
> !MESSAGE Initializing from the application definition instance yields no top-level windows! Continuing execution, but the missing windows may cause other initialization failures.
> !STACK 0
> java.lang.Exception
>     at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadMostRecentModel(ResourceHandler.java:246)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:435)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:260)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:146)
>     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
>     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
>     at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
>     at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
> 
> !ENTRY org.eclipse.osgi 4 0 2015-11-25 14:57:07.056
> !MESSAGE Application error
> !STACK 1
> java.lang.NullPointerException
>     at org.eclipse.e4.ui.internal.workbench.ResourceHandler.loadMostRecentModel(ResourceHandler.java:250)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application.loadApplicationModel(E4Application.java:435)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application.createE4Workbench(E4Application.java:260)
>     at org.eclipse.e4.ui.internal.workbench.swt.E4Application.start(E4Application.java:146)
>     at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
>     at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
>     at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke(Method.java:497)
>     at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
>     at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
>     at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
>     at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

Do I need to create an e4xmi myself, or am I missing something else?

Thanks for your thoughts!

**Comment by aonoiwa** [comment]
Could it be that you must use "gradle scaffold" to create the files.
I haven´t done the tutorials yet, so no guarantee it solves your problem....
