### ISSUE TITLE
build fails on :libs:unpuzzle:installEclipse

### ISSUE THREAD

**Issue by carlolf** [akhikhl/wuff#3]
After cloning the git repository, I did a "gradle build" (on Windows 7, using Jdk1.7 and Gradle 1.11).
Here is the important stack trace:

```
Caused by: : Problem: failed to create task or type pom
Cause: The name is undefined.
Action: Check the spelling.
Action: Check that any custom tasks/types have been declared.
Action: Check that any <presetdef>/<macrodef> declarations have taken place.

        at org.apache.tools.ant.UnknownElement.getNotFoundException(UnknownElement.java:499)
        at org.apache.tools.ant.UnknownElement.makeObject(UnknownElement.java:431)
        at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:163)
        at org.akhikhl.unpuzzle.osgi2maven.Deployer$_deployBundle_closure2.doCall(Deployer.groovy:84
)
        at org.akhikhl.unpuzzle.osgi2maven.Deployer.deployBundle(Deployer.groovy:83)
        at org.akhikhl.unpuzzle.osgi2maven.Deployer$deployBundle.call(Unknown Source)
        at org.akhikhl.unpuzzle.eclipse2maven.EclipseDeployer$_deploy_closure2_closure8.doCall(Eclip
seDeployer.groovy:168)
        at org.akhikhl.unpuzzle.eclipse2maven.EclipseDeployer$_deploy_closure2.doCall(EclipseDeploye
r.groovy:167)
        at org.akhikhl.unpuzzle.eclipse2maven.EclipseDeployer.deploy(EclipseDeployer.groovy:166)
        at org.akhikhl.unpuzzle.eclipse2maven.EclipseDeployer$deploy.call(Unknown Source)
        at org.akhikhl.unpuzzle.Configurer.installEclipse(Configurer.groovy:145)
        at org.akhikhl.unpuzzle.Configurer$_apply_closure2_closure7_closure14.doCall(Configurer.groo
vy:66)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:502)
```

Please note, the same fail occurs if I do a build on "IdeApp-8" example.

**Comment by ErikaRedmark** [comment]
From my understanding, this fix was supposed to target 0.13? I am using that version and I just encountered the same issue. Removing the spaces from the path fixed the issue, so it appears to still be occurring in the latest release.

For reference, I am using Windows as well with JDK 1.7.0_17-b02

**Comment by akhikhl** [comment]
No, it wasn't fixed. It just that our colleagues found workaround (use path without spaces).
Is it a blocker for you?

**Comment by ErikaRedmark** [comment]
Blocker may be too strong the word, but it does mean I must rename several project folders. I'm worried  however that when we integrate the Gradle builds with our CI server Bamboo, I cannot confirm if all the paths on the remote agents will be space-free. 

To sum up: not a blocker at this instant, but there exists a good chance it could be a time bomb.

**Comment by akhikhl** [comment]
I'll see to fixing it.

**Comment by ErikaRedmark** [comment]
Thank you. I'll continue following this issue in the event you want/need me to test the fix.

**Comment by twindham** [comment]
I'm just getting started with using Wuff.  I was following the steps here... https://github.com/akhikhl/wuff/wiki/Convert-existing-Eclipse-plugins-and-apps-to-Gradle and I couldn't understand why my hello world projects wouldn't build.  Took me a while to find this page and try the work around of removing spaces from the directory names.  Is there an issue created just for this issue.  I wouldn't mind taking a crack at fixing it.

**Comment by jGleitz** [comment]
Hi there

We are running into this issue (wuff fails if a space is in the project path) in the moment (on Windows and Linux). It’s a major inconvenience for us.

Any chances that this will be fixed soon?
