### ISSUE TITLE
Wuff build failed with exception

### ISSUE THREAD

**Issue by JBarbuletis** [akhikhl/wuff#88]
Hi,
After wuff's last update i can't build my project. I get exception:

:log4jproject:compileJava UP-TO-DATE
:log4jproject:createExtraFiles UP-TO-DATE
:log4jproject:processResources UP-TO-DATE
:log4jproject:classes UP-TO-DATE
:log4jproject:createOsgiManifest UP-TO-DATE
:log4jproject:jar UP-TO-DATE
:converter:compileJava UP-TO-DATE
:converter:createExtraFiles UP-TO-DATE
:converter:processResources UP-TO-DATE
:converter:classes UP-TO-DATE
:converter:createOsgiManifest UP-TO-DATE
:converter:jar UP-TO-DATE
:converter:assemble UP-TO-DATE
:converter:compileTestJava UP-TO-DATE
:converter:processTestResources UP-TO-DATE
:converter:testClasses UP-TO-DATE
:converter:test UP-TO-DATE
:converter:check UP-TO-DATE
:converter:build UP-TO-DATE
:datamodel:compileJava UP-TO-DATE
:datamodel:createExtraFiles UP-TO-DATE
:datamodel:processResources UP-TO-DATE
:datamodel:classes UP-TO-DATE
:datamodel:createOsgiManifest UP-TO-DATE
:datamodel:jar UP-TO-DATE
:dbapi:compileJava UP-TO-DATE
:dbapi:createExtraFiles UP-TO-DATE
:dbapi:processResources UP-TO-DATE
:dbapi:classes UP-TO-DATE
:dbapi:createOsgiManifest UP-TO-DATE
:dbapi:jar UP-TO-DATE
:file-manager:compileJava UP-TO-DATE
:file-manager:createExtraFiles UP-TO-DATE
:file-manager:processResources UP-TO-DATE
:file-manager:classes UP-TO-DATE
:file-manager:createOsgiManifest UP-TO-DATE
:file-manager:jar UP-TO-DATE
:orientdb:compileJava UP-TO-DATE
:orientdb:createExtraFiles UP-TO-DATE
:orientdb:processResources UP-TO-DATE
:orientdb:classes UP-TO-DATE
:orientdb:createOsgiManifest UP-TO-DATE
:orientdb:jar UP-TO-DATE
:web service proxy:compileJava UP-TO-DATE
:web service proxy:createExtraFiles UP-TO-DATE
:web service proxy:processResources UP-TO-DATE
:web service proxy:classes UP-TO-DATE
:web service proxy:createOsgiManifest UP-TO-DATE
:web service proxy:jar UP-TO-DATE
:data-manager:compileJava UP-TO-DATE
:data-manager:createExtraFiles UP-TO-DATE
:data-manager:processResources UP-TO-DATE
:data-manager:classes UP-TO-DATE
:data-manager:createOsgiManifest UP-TO-DATE
:data-manager:jar UP-TO-DATE
:data-manager:assemble UP-TO-DATE
:data-manager:compileTestJava UP-TO-DATE
:data-manager:processTestResources UP-TO-DATE
:data-manager:testClasses UP-TO-DATE
:data-manager:test UP-TO-DATE
:data-manager:check UP-TO-DATE
:data-manager:build UP-TO-DATE
:datamodel:assemble UP-TO-DATE
:datamodel:compileTestJava UP-TO-DATE
:datamodel:processTestResources UP-TO-DATE
:datamodel:testClasses UP-TO-DATE
:datamodel:test UP-TO-DATE
:datamodel:check UP-TO-DATE
:datamodel:build UP-TO-DATE
:dbapi:assemble UP-TO-DATE
:dbapi:compileTestJava UP-TO-DATE
:dbapi:processTestResources UP-TO-DATE
:dbapi:testClasses UP-TO-DATE
:dbapi:test UP-TO-DATE
:dbapi:check UP-TO-DATE
:dbapi:build UP-TO-DATE
:file-manager:assemble UP-TO-DATE
:file-manager:compileTestJava UP-TO-DATE
:file-manager:processTestResources UP-TO-DATE
:file-manager:testClasses UP-TO-DATE
:file-manager:test UP-TO-DATE
:file-manager:check UP-TO-DATE
:file-manager:build UP-TO-DATE
:log4jproject:assemble UP-TO-DATE
:log4jproject:compileTestJava UP-TO-DATE
:log4jproject:processTestResources UP-TO-DATE
:log4jproject:testClasses UP-TO-DATE
:log4jproject:test UP-TO-DATE
:log4jproject:check UP-TO-DATE
:log4jproject:build UP-TO-DATE
:orientdb:assemble UP-TO-DATE
:orientdb:compileTestJava UP-TO-DATE
:orientdb:processTestResources UP-TO-DATE
:orientdb:testClasses UP-TO-DATE
:orientdb:test UP-TO-DATE
:orientdb:check UP-TO-DATE
:orientdb:build UP-TO-DATE
:rcpview:compileJava UP-TO-DATE
:rcpview:createExtraFiles UP-TO-DATE
:rcpview:processResources UP-TO-DATE
:rcpview:classes UP-TO-DATE
:rcpview:createOsgiManifest UP-TO-DATE
:rcpview:jar UP-TO-DATE
:rcpview:assemble UP-TO-DATE
:rcpview:wrapLibs UP-TO-DATE
:rcpview:buildProduct_windows_x86_64 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rcpview:buildProduct_windows_x86_64'.
> Cannot get property 'url' on null object

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':rcpview
:buildProduct_windows_x86_64'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExec
uter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailur
e(AbstractTask.java:310)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
tTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
ltTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
ExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecu
ter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
ecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildCon
troller.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
cuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
ctionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe
cute(DaemonUsageSuggestingBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.exe
cute(DaemonUsageSuggestingBuildActionExecuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.jav
a:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.
execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRunti
meValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(
CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionRep
ortingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBoots
trap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.j
ava:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.ja
va:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Caused by: java.lang.NullPointerException: Cannot get property 'url' on null obj
ect
        at org.akhikhl.unpuzzle.eclipse2maven.EclipseDeployer.getUnpackDir(Eclip
seDeployer.groovy:29)
        at org.akhikhl.unpuzzle.eclipse2maven.EclipseDeployer$getUnpackDir$0.cal
l(Unknown Source)
        at org.akhikhl.wuff.EquinoxProductConfigurer.getDeltapackDir(EquinoxProd
uctConfigurer.groovy:425)
        at org.akhikhl.wuff.EquinoxProductConfigurer.writeNativeLauncher(Equinox
ProductConfigurer.groovy:373)
        at org.akhikhl.wuff.EquinoxProductConfigurer$_configureBuildTask_closure
1_closure14.doCall(EquinoxProductConfigurer.groovy:147)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(Abstra
ctTask.java:558)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(Abstra
ctTask.java:539)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:61)
        ... 49 more

And my gradle.build file:

buildscript {
  repositories {
    mavenLocal()
    jcenter()
  }

  dependencies {
    classpath 'org.akhikhl.wuff:wuff-plugin:+'
  }
}

subprojects {

  repositories {
    mavenLocal()
	jcenter()
  }

  apply plugin: 'java'

  if(name == 'rcpview')
    apply plugin: 'org.akhikhl.wuff.eclipse-rcp-app'
  else
    apply plugin: 'org.akhikhl.wuff.eclipse-bundle'
}

Before update this error didn't occure. Please help me resolve this problem. Thanks.

**Comment by nedtwigg** [comment]
Might wanna take a look at [Goomph](https://github.com/diffplug/goomph) and its [example project](https://github.com/diffplug/gradle_and_eclipse_rcp).  Currently on 3.0.0-SNAPSHOT, actively seeking feedback before 3.0.0 release.
