### ISSUE TITLE
No such property: Base64

### ISSUE THREAD

**Issue by PeWolf** [akhikhl/wuff#99]
Hi,

I want to use wuff behind a firewall.
With "gradle task"  i've got the following output:
Downloading file: http://mirror.netcologne.de/eclipse//technology/epp/downloads/release/luna/SR2/eclipse-jee-luna-SR2-win32-x86_64.zip

FAILURE: Build failed with an exception.
....
Caused by: java.net.ConnectException: Connection timed out: connect
        at org.akhikhl.unpuzzle.utils.Downloader.downloadFile(Downloader.groovy:80)
##         at org.akhikhl.unpuzzle.utils.Downloader$downloadFile.call(Unknown Source)

With "gradle -Dhttp.proxyHost=myProxy -Dhttp.proxyPort=myProxy -Dhttp.proxyUser=MyUser -Dhttp.proxyPassword=myPassword tasks" i've got following output:
...
 No such property: Base64 for class: org.akhikhl.unpuzzle.utils.Downloader
...
Caused by: groovy.lang.MissingPropertyException: No such property: Base64 for class: org.akhikhl.unpuzzle.utils.Downloader
        at org.akhikhl.unpuzzle.utils.Downloader.openConnection(Downloader.groovy:102)
##         at org.akhikhl.unpuzzle.utils.Downloader.downloadFile(Downloader.groovy:69)

I know that Base64 is a java8 class. I start gradle with Java8. So, what went wrong?
I use Gradle 2.7, JVM 1.8.0_51, wuff 0.0.20, unpuzzle 0.0.22.

Does anybody know where the problem is?

**Comment by Arun4D** [comment]
hi
Are you able to fix this problem?

**Comment by bueli** [comment]
Looks lik a name conflict to me. 
org.apache.commons.io.IOUtils.Base64 vs java.util.Base64
Will look into it this week ...

**Comment by Arun4D** [comment]
Thanks Bueli
